prepare:
  sequence_length: 10
  random_state: 42

model:
  input_size: 12
  num_classes: 2

optuna:
  n_trials: 10
  timeout: 3600
  study_name: gru_fraud_detection
  direction: maximize
  # (optional) hyperparameter ranges used later in your script
  hyperparameters:
    batch_size:
      type: choice
      choices: [32, 64, 128]
    hidden_size:
      type: int
      low: 32
      high: 256
    num_layers:
      type: int
      low: 1
      high: 3
    dropout:
      type: float
      low: 0.0
      high: 0.5
    learning_rate:
      type: float
      low: 1.0e-5
      high: 1.0e-2
    optimizer:
      type: choice
      choices: [adam, adamw, sgd]

training:
  final_epochs: 50
  early_stopping_patience: 15

mlflow:
  experiment_name: credit_card_fraud_detection
  # tracking_uri: http://127.0.0.1:5000
